### PR TITLE
Support multiple reactions in ratio constraints…

### PR DESCRIPTION
**Pull request by joaocardoso**
I changed the add_ratio_constraint method to support adding multiple reactions, linear expressions or lists of reactions to make it possible to create constraints such as:
- v1/(v2 + v3) = r
- (v1 + v2)/v3 = r
- (v1 + v2)/(v3 + v4) = r
- (2 v1 + v2) / v3 = r
- etc...

### CODE REVIEW

**Comment by joaocardoso** [comment]
@hredestig agreed, I'll try to add some over the weekend.

**Comment by phantomas1234** [comment]
Can we please move this forward. We certainly have tendency to let PRs get stale.

**Comment by phantomas1234** [comment]
@hredestig can you finish this one?

**Comment by hredestig** [comment]
depends on #89 to pass tests

**Pull request merged**
