### PR TITLE
Use travis-sphinx to publish cameo docs to GitHub pages

### PR DESCRIPTION
**Pull request by phantomas1234**
https://github.com/Syntaf/travis-sphinx

### CODE REVIEW

**Comment by phantomas1234** [comment]
@hredestig Ok, docs publishing to the gh-pages branche should be fully automatic now. Need to decide if this should only happen on master eventually.

**Comment by Midnighter** [comment]
You can use some variation of:
```
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
```
which will run only when successful, on branch master, and not for PRs. Or use a script for deployment.

**Comment by phantomas1234** [comment]
@Midnighter this looks like a much cleaner option, let me try this first @hredestig  before merging.

**Comment by phantomas1234** [comment]
I am going to merge this one using my admin privileges because I can't test it because travis-ci stopped running the PR branch.

**Pull request merged**
