### PR TITLE
Update analysis.py

### PR DESCRIPTION
**Pull request by matthiaskoenig**
Incorrect return type documented which is confusing for usage.

### CODE REVIEW

**Review by carrascomj — COMMENTED** [review]
LGTM, but it needs to be rebased.

**Comment by matthiaskoenig** [comment]
Basically, I pulled the latest upstream changes in my fork and rebased against devel. I hope this is what you meant.

**Comment by carrascomj** [comment]
flake8 failed with an E501: line too long.

**Review by carrascomj — APPROVED** [review]

**Comment by phantomas1234** [comment]
Thanks @matthiaskoenig!

**Pull request merged**
